# Generated by Django 4.2.2 on 2023-06-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IFish', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default='2023-06-17 10:21:07.354153'),
            preserve_default=False,
        ),
    ]
